### ISSUE TITLE
Feature Request: Option to Hide Suggested Posts, Reels, Stories, and "People You May Follow" + Messenger Issue

### ISSUE THREAD

**Issue by qomarhsn** [ycngmn/Nobook#5]
Hi! Thanks for developing Nobook — it’s a fantastic, lightweight Facebook browsing experience.

I’d like to request adding options to hide:
- Suggested posts
- People You May Know section
- Story section
- Reels section

Also, when trying to open the **Messenger tab**, it displays the following message and blocks access:

> "Use Messenger to keep chatting. Chats on mobile browsers aren’t available. Go to Messenger."

Here is a screenshot for reference:
![Image](https://github.com/user-attachments/assets/8ba01601-e570-44c2-aa3b-96366903b68d)

Thanks again for your awesome work!

**Comment by qomarhsn** [comment]
> Have you updated to the latest version yet? The option to disable suggested posts can be enabled in settings. For the messages tab, it opens in Nobook with no problem on my side.

Yes, I got the suggested posts option in the updated version. I've spoken to a few other users about the Messenger issue—some are experiencing it, while others are not.

**Comment by ycngmn** [comment]
Hello, thanks for your repot.
If you have the **messenger** app installed on your phone, that's the expected behaviour as Nobook isn't intended to support all the messenger's functionalities. Normally, it should automatically redirect you to the messenger app.

If that's not the case, can you kindly provide :
* Your phone's model & Android version.
* The version of the "webview" app. ( it's a system app. you can locate it from `settings -> all apps` )

**Comment by JunkyardCat** [comment]
so im not the original poster
@ycngmn 
i also experience the same thing as the original poster. i did uninstall messenger but still encounter the message 

phone: galalxy a05s. android 14 oneui 6.1

webview:135.0.7049.111

**Comment by qomarhsn** [comment]
@ycngmn 
The problem persists even if Messenger is not installed.
Mobile: Redmi Note 12 5G, Android 15 (CR Droid)
WebView Version: 134.0.6998.95

**Comment by ycngmn** [comment]
As I am not able to reproduce the bug, I have assumed a probable cause and applied a probable fix. Would you kindly let me know if that fixes your issue by updating the app from this link ?

[app-release.zip](https://github.com/user-attachments/files/19972330/app-release.zip)

If the bug still occurs, I will try to add a radical fix. 
Thanks a lot for your help guys.

**Comment by qomarhsn** [comment]
@ycngmn 
Perhaps the problem is not with nobook. Since this is a webview of the m.facebook.com, I visited this site from a regular browser and saw the same thing. Perhaps Facebook itself has blocked the use of Messenger from the webview (Maybe under some requirements). You can see if there is a system that can be added to bypass this.

**Comment by ycngmn** [comment]
> [@ycngmn](https://github.com/ycngmn) Perhaps the problem is not with nobook. Since this is a webview of the m.facebook.com, I visited this site from a regular browser and saw the same thing. Perhaps Facebook itself has blocked the use of Messenger from the webview (Maybe under some requirements). You can see if there is a system that can be added to bypass this.

There is already added an workaround on the app but apparently for some reason that's not working on some system. Can you confirm if you have other issues like "open app" banner on bottom or the topbar dissapearing on scroll ?

**Comment by qomarhsn** [comment]
> > [@ycngmn](https://github.com/ycngmn) Perhaps the problem is not with nobook. Since this is a webview of the m.facebook.com, I visited this site from a regular browser and saw the same thing. Perhaps Facebook itself has blocked the use of Messenger from the webview (Maybe under some requirements). You can see if there is a system that can be added to bypass this.
> There is already an workaround on the app but apparently for some reason that's not working on some system. Can you confirm if you have other issues like "open app" banner on bottom or the topbar dissapearing on scroll ? 



I haven't faced any issues like 'open app' banner and topbar disappearing.

**Comment by MF-Debug** [comment]
> There is already an workaround on the app but apparently for some reason that's not working on some system. Can you confirm if you have other issues like "open app" banner on bottom or the topbar dissapearing on scroll ?

I'm facing this issue where I see a 'open app' banner on bottom of the app.
I'm on v0.0.2 running HyperOS 2 (A15) on POCO X6 Pro 5G. My webview v136.0.7103.60.

**Comment by Bakr-Ali** [comment]
> As I am not able to reproduce the bug, I have assumed a probable cause and applied a probable fix. Would you kindly let me know if that fixes your issue by updating the app from this link ?
> 
> [app-release.zip](https://github.com/user-attachments/files/19972330/app-release.zip)
> 
> If the bug still occurs, I will try to add a radical fix. Thanks a lot for your help guys.

Installed this and still messages not showing. 

- Device: Samsung Galaxy S23+
- OS: Android 14 / OneUI 6.1
- Facebook and Messenger are not installed.

**Comment by LatringDay** [comment]
Messsnger not working for me either.

CMF phone 1
Android 15
Nothing From meta is installed

**Comment by 0-BlackSpectrum-0** [comment]
I too have the same issue, I think it's not a region issue since I tried using VPN to connect to 2 different locations.
I'm running Android 11 based on one ui 3.1 on Samsung M30s.

Also option to hide reels and people you may know would be nice to have.

**Comment by malasone** [comment]
I also cant see messages.

- S23
- OneUI 7 / Android 15
- FB, Messenger, and IG are installed if that matters

**Comment by ycngmn** [comment]
Thank you guys! 
After a long run on multiple devices and emulators alike, I reproduced a simillar issue by using an Iphone 6 user agent. lol.

If it was an user-agent related issue, like I initially thought, it should have been fixed in the last v0.0.3 update. 
Now I've applied an ugly fix that hopefully should ressolve the issue. 

To help investigate further, could you please provide your user-agent string?
You can use any phone browser and get it via this link: https://whatmyuseragent.com/

>For those encountering other issues—such as non-Facebook URLs opening in the app instead of your browser, or unexpected UI inconsistencies—please create a separate issue and include your user-agent string there as well.

Thanks again.

**Comment by Bakr-Ali** [comment]
> Thank you guys! After a long run on multiple devices and emulators alike, I reproduced a simillar issue by using an Iphone 6 user agent. lol.
> 
> If it was an user-agent related issue, like I initially thought, it should have been fixed in the last v0.0.3 update. Now I've applied an ugly fix that hopefully should ressolve the issue.
> 
> To help investigate further, could you please provide your user-agent string? You can use any phone browser and get it via this link: https://whatmyuseragent.com/
> 
> > For those encountering other issues—such as non-Facebook URLs opening in the app instead of your browser, or unexpected UI inconsistencies—please create a separate issue and include your user-agent string there as well.
> 
> Thanks again.

Installing v0.0.3 didn't fix the Messenger issue

User agent in chrome is: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by ycngmn** [comment]
Can anyone please try and confirm if it's finally working in the latest release ?

**Comment by 0-BlackSpectrum-0** [comment]
It's working for me now.

**Comment by qomarhsn** [comment]
> Can anyone please try and confirm if it's finally working in the latest release ?

Messenger is working. But there are some problems. Which I mentioned in issue #21 . And the story is not being hidden. Even after turning on it on from the settings. And sometimes Reels and 'People You May Know' are also showing.

**Comment by 0-BlackSpectrum-0** [comment]
Oh yeah just now noticed additional settings were added, for me too "people you may know" doesn't go, also I'm getting posts from the people I don't follow, (with a blue follow button on top) are they suggested posts? If they are then it's also not working and if not, can that be removed as well?

**Comment by ycngmn** [comment]
Please create a new issue with screenshots to help understand the issue better.
